### ISSUE TITLE
whatsnew_linkプラグインを有効にした後に再起動すると起動できなくなる。

### ISSUE THREAD

**Issue by satoryu** [tdiary/tdiary-blogkit#13]
Heroku上で運用中のtDiaryに、Blogkitを適用し、再起動した後、起動できなかった。

再起動時のログは下記のように、whatnew-listプラグインが起動時に呼び出している`whatnew_list_update` 内で、`diary`が想定したものを取得できていないように見える。

```
2017-07-09T10:02:45.946909+00:00 app[web.1]: NoMethodError: undefined method `title' for nil:NilClass
2017-07-09T10:02:45.945791+00:00 app[web.1]: bundler: failed to load command: thin (/app/vendor/bundle/ruby/2.4.0/bin/thin)
2017-07-09T10:02:45.946910+00:00 app[web.1]:   (plugin/whatsnew-list.rb):190:in `whatsnew_list_update'
2017-07-09T10:02:45.946911+00:00 app[web.1]:   (plugin/whatsnew-list.rb):252:in `block (2 levels) in load_plugin'
2017-07-09T10:02:45.946914+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.4.0/gems/tdiary-5.0.5/lib/tdiary/application.rb:126:in `run_plugin_startup_procs'
2017-07-09T10:02:45.946912+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.4.0/gems/tdiary-5.0.5/lib/tdiary/plugin.rb:340:in `block in startup_proc'
2017-07-09T10:02:45.946914+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.4.0/gems/tdiary-5.0.5/lib/tdiary/plugin.rb:339:in `startup_proc'
2017-07-09T10:02:45.946913+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.4.0/gems/tdiary-5.0.5/lib/tdiary/plugin.rb:339:in `each'
2017-07-09T10:02:45.946917+00:00 app[web.1]:   config.ru:16:in `block in <main>'
2017-07-09T10:02:45.946918+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/builder.rb:55:in `instance_eval'
2017-07-09T10:02:45.946916+00:00 app[web.1]:   config.ru:16:in `new'
2017-07-09T10:02:45.946915+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.4.0/gems/tdiary-5.0.5/lib/tdiary/application.rb:58:in `initialize'
2017-07-09T10:02:45.946918+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/builder.rb:55:in `initialize'
2017-07-09T10:02:45.946919+00:00 app[web.1]:   config.ru:1:in `new'
2017-07-09T10:02:45.946922+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.4.0/gems/thin-1.7.0/lib/thin/controllers/controller.rb:182:in `load_rackup_config'
2017-07-09T10:02:45.946919+00:00 app[web.1]:   config.ru:1:in `<main>'
2017-07-09T10:02:45.946920+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.4.0/gems/thin-1.7.0/lib/rack/adapter/loader.rb:33:in `eval'
2017-07-09T10:02:45.946921+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.4.0/gems/thin-1.7.0/lib/rack/adapter/loader.rb:33:in `load'
2017-07-09T10:02:45.946924+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.4.0/gems/thin-1.7.0/lib/thin/runner.rb:156:in `run!'
2017-07-09T10:02:45.946924+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.4.0/gems/thin-1.7.0/bin/thin:6:in `<top (required)>'
2017-07-09T10:02:45.946923+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.4.0/gems/thin-1.7.0/lib/thin/runner.rb:200:in `run_command'
2017-07-09T10:02:45.946922+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.4.0/gems/thin-1.7.0/lib/thin/controllers/controller.rb:72:in `start'
2017-07-09T10:02:45.946925+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.4.0/bin/thin:22:in `load'
2017-07-09T10:02:45.946926+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.4.0/bin/thin:22:in `<top (required)>'
2017-07-09T10:02:46.093326+00:00 heroku[web.1]: Process exited with status 1
```

## 環境

* tdiary 5.0.5
* tdiary-blogkit 5.0.4
* ruby 2.4.0-p0

**Comment by tdtds** [comment]
何が起きているのかはだいたい想像がつくんですが、似たようなコードがcoreのmakerssプラグインでは動いているので、条件をもうちょっと絞りたい感じですね。ご協力願えますか?

このルートは、(Herokuのようなファイルシステムが揮発性のサーバで)tDiary起動時にrssファイルを再生成するために走ります。今回(おそらく)おかしなことになっているのは@dateと@diariesなんですが、これらの初期値はcoreのapplication.rbで設定されているはずなんですね。なので、これらがどんな値の時に問題を起こすのか知りたいです。

**Comment by satoryu** [comment]
エラーが起きた行の直前の`@date`を調べてみたところ、落ちる直前にtdiaryを起動した日時が`@date`に入っていて、日記を書いていないとその日の日記が`@diaries`には存在しないので、`nil`の状態でそのまま処理が続いているようです。

**Comment by satoryu** [comment]
`lib/tdiary/application.rb` を見ると、`TDiary::Plugin` のインスタンスを作成する時に`'date' => Time.now` を渡していますね。

**Comment by satoryu** [comment]
あらためて調べてみると、`@diaries` が空のHashになっていました。
日記自体は数件あるのですが。。。

**Comment by tdtds** [comment]
プラグイン機構のstartup_procはかなり限定的な状況で呼ばれるので、プラグインが想定している環境がいろいろ足りてないんですよね。ちょっと調べてみます。

**Comment by tdtds** [comment]
直ったと思います〜

**Comment by satoryu** [comment]
@tdtds 起動できるようになりました！ 🎉
